version: 2.1

orbs:
  python: circleci/python@1.3.2
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  run-ui-tests:
    docker:
      - image: cimg/python:3.10.12-browsers

    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - python/install-packages:
          pkg-manager: pip
          cache-version: v4
          include-branch-in-cache-key: false
      - run:
          name: Install Allure commandline
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk wget
            wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
            sudo tar -xvzf allure-commandline-2.17.2.tgz -C /opt
            sudo ln -s /opt/allure-2.17.2/bin/allure /usr/bin/allure

      - run:
          name: Run tests with Allure
          no_output_timeout: 15m
          command: |
            mkdir test-results
            pytest --alluredir=allure-results --junitxml=test-results/junit.xml
      
      - run:
          name: Generate Allure report
          command: |
              sudo npm install -g allure-commandline
              echo BRANCH=development >> allure-results/environment.properties
              echo COMMIT=$CI_PULL_REQUEST/commits/$CIRCLE_SHA1 >> allure-results/environment.properties
              allure generate --clean
          when: always

      - store_artifacts:
          path: allure-report
          destination: allure-report
          when: always

      - store_test_results:
          path: test-results


workflows:
  ui-tests:
    jobs:
      - run-ui-tests
