name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xdist
          pip install -r requirements.txt

      - name: Run tests with pytest-xdist
        run: pytest -n auto --alluredir=allure-report

      - name: Install Allure command line
        run: |
          curl -o allure-2.14.0.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.tgz
          sudo tar -zxvf allure-2.14.0.tgz -C /opt
          sudo ln -s /opt/allure-2.14.0/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure report
        run: allure generate --clean --output allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
